# Generated by Django 5.0 on 2024-05-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_events_event_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='storyLink',
        ),
    ]
